### PR TITLE
bump dependencies

### PR DESCRIPTION
**Pull request by nijikon**

### CODE REVIEW

**Comment by nijikon** [comment]
@mfazekas locally it builds on `2.4.0`. I don't know why Travis did not pick this up, can you check?

**Comment by nijikon** [comment]
Ping

**Comment by mfazekas** [comment]
@nijikon Thanks much for the PR. Can you describe the problem you're solving?

As for travis this repo doesn't seems to have travis enabled. (I don't have right to enabe it)

**Comment by nijikon** [comment]
@mfazekas First I wanted to bump all the dependencies gradually. After everything is up to date, I will try to make it work with rbnacl >= 5.x. Cause right now it's not working for me, and I don't know why.

**Comment by mfazekas** [comment]
@nijikon rbnacl should be a development only dependency (only required for tests)

**Comment by nijikon** [comment]
@mfazekas any particular reason that `ed25519 support` is not possible with `rbnacl >= 5`?

**Comment by mfazekas** [comment]
@nijikon You mean ed25519 support should work with rbnacl 5 in net-ssh? I don't think the bcrypt_pbkdf-ruby has to do anything with that. 

It's more likely the versions in net-ssh needs to be updated: 
https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/authentication/ed25519.rb

**Comment by nijikon** [comment]
@mfazekas you were completely right. I updated `rbnacl` here net-ssh/net-ssh#555. I think that we still can bump dependencies here so we have it running the latest versions. What do you think?

**Pull request closed without merging**
