### PR TITLE
new action release workflow to build, tag, and publish

### PR DESCRIPTION
**Pull request by h0tw1r3**
Blocked by
- [ ] #22

### CODE REVIEW

**Comment by h0tw1r3** [comment]
> On gem publishing is it possible to enforce MFA, so GitHub actions you'd have to enter the OTP to publish a new release?

@mfazekas The only way I know of doing that is using a step that provides an MFA gate:
https://github.com/step-security/wait-for-secrets

**Comment by mfazekas** [comment]
> > On gem publishing is it possible to enforce MFA, so GitHub actions you'd have to enter the OTP to publish a new release?
> 
> @mfazekas The only way I know of doing that is using a step that provides an MFA gate: https://github.com/step-security/wait-for-secrets

Thanks much, tried to use GitHub actions input and the GEM_HOST_OTP_CODE variable. That works but somehow the 
```
        NET_SSH_BUILDGEM_SIGNED=1 GEM_HOST_OTP_CODE=${{ inputs.one_time_password }} bundle exec rake release
        NET_SSH_BUILDGEM_SIGNED=1 GEM_HOST_OTP_CODE=${{ inputs.one_time_password }} bundle exec rake gem:release
```

`gem:release` fails.

```log
bcrypt_pbkdf 1.1.1.rc1 built to pkg/bcrypt_pbkdf-1.1.1.rc1.gem.
Tag v1.1.1.rc1 has already been created.
Pushing gem to https://rubygems.org.../
Successfully registered gem: bcrypt_pbkdf (1.1.1.rc1)
Pushed bcrypt_pbkdf 1.1.1.rc1 to rubygems.org
gem push pkg/bcrypt_pbkdf-1.1.1.rc1-arm64-darwin.gem
ERROR:  While executing gem ... (Gem::Package::FormatError)
    No such file or directory @ rb_sysopen - pkg/bcrypt_pbkdf-1.1.1.rc1-arm64-darwin.gem
rake aborted!
Command failed with status (1): [gem push pkg/bcrypt_pbkdf-1.1.1.rc1-arm64-darwin.gem]
/home/runner/work/net-ssh-release/net-ssh-release/bcrypt_pbkdf-ruby/Rakefile:71:in `block (4 levels) in <top (required)>'
/home/runner/work/net-ssh-release/net-ssh-release/bcrypt_pbkdf-ruby/Rakefile:86:in `block (3 levels) in <top (required)>'
/home/runner/work/net-ssh-release/net-ssh-release/bcrypt_pbkdf-ruby/Rakefile:85:in `each'
/home/runner/work/net-ssh-release/net-ssh-release/bcrypt_pbkdf-ruby/Rakefile:85:in `block (2 levels) in <top (required)>'
/opt/hostedtoolcache/Ruby/3.1.0/x64/bin/bundle:25:in `load'
/opt/hostedtoolcache/Ruby/3.1.0/x64/bin/bundle:25:in `<main>'
```

**Comment by mfazekas** [comment]
@h0tw1r3 I've added release actions into a private repo. I've released 1.1.1.rc2 https://rubygems.org/gems/bcrypt_pbkdf pls test and let me know

**Comment by h0tw1r3** [comment]
@mfazekas looks good to me! Tested with puppet Bolt https://github.com/puppetlabs/bolt/pull/3317

**Pull request closed without merging**
