### PR TITLE
Build fixes and improvements

### PR DESCRIPTION
**Pull request by h0tw1r3**
* Fix building gem on Windows (all compilers)
* Replace travis workflow with github action workflow to test building on windows, linux, and mac
* Add release workflow to publish native gems for mac and windows

### CODE REVIEW

**Comment by h0tw1r3** [comment]
Release workflow requires setting up a `RUBYGEMS_OIDC_API_ROLE` secret.
See https://github.com/rubygems/configure-rubygems-credentials for more details

**Comment by mfazekas** [comment]
@h0tw1r3 thanks much, looks great!

On gem publishing is it possible to enforce MFA, so GitHub actions you'd have to enter the OTP to publish a new release?

**Comment by h0tw1r3** [comment]
@mfazekas separated the release workflow out into #23 as it's a separate thing I think.

**Review by mfazekas — APPROVED** [review]

**Comment by mfazekas** [comment]
@h0tw1r3 thanks much!

**Pull request merged**
